apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ox5x
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ijcc-tenant/rhtap-demo-app/hacbs-test-project-ox5x@sha256:d6d83ea456daa79734d55291010fe13f526326a7d02f658605f7ecb957a6dcc4
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
