apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-ox5x
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ijcc-tenant/rhtap-demo-app/hacbs-test-project-ox5x@sha256:df238a103ce3820e1a77c0667ac3fc3fc53265dc6e458d80d407b2961307a6d6
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
